const localProducts=[
{id:'p_001',name:'NAS Backup Audit Tool',slug:'nas-backup-audit-tool',price:249,platform:'Windows',seller:'APC Utilities',type:'Operations Tool',category:'operations',status:'active',desc:'Audit NAS folders, storage sizes and backup structure with clear technical reporting.',badge:'BACKUP & AUDIT',icon:'◫'},
{id:'p_002',name:'ESP32 Gate HMI Pack',slug:'esp32-gate-hmi-pack',price:399,platform:'ESP32',seller:'Wykies Automation',type:'Firmware Package',category:'embedded',status:'active',desc:'Embedded gate-control package with responsive local HMI, firmware and documentation.',badge:'EMBEDDED CONTROL',icon:'▦'},
{id:'p_003',name:'PlantLink Gateway',slug:'plantlink-gateway',price:0,platform:'Windows / OPC',seller:'Wykies Automation',type:'Industrial Gateway',category:'automation',status:'preview',desc:'A practical industrial data gateway concept for controlled OPC-based integration.',badge:'INDUSTRIAL DATA',icon:'⌁'},
{id:'p_004',name:'LoopPilot',slug:'looppilot',price:0,platform:'Windows',seller:'Wykies Automation',type:'Engineering Platform',category:'engineering',status:'preview',desc:'Loop readiness, instrument validation and PID advisory workflows in one focused platform.',badge:'PROCESS ENGINEERING',icon:'◇'}
];
let products=[...localProducts];
function money(n){return Number(n)>0?'R '+Number(n).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2}):'Preview'}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const t=await r.text();try{return JSON.parse(t)}catch{return t}}
async function tryLoadBackendProducts(){try{const rows=await api('/api/public/products');if(Array.isArray(rows)&&rows.length){products=rows.map((p,i)=>({id:p.id,name:p.name,slug:p.slug,price:p.price,platform:p.platform||'Software',seller:p.sellerName||p.seller||'Seller',type:p.type||p.category||'Software Tool',category:String(p.category||p.type||'software').toLowerCase(),status:p.status||'active',desc:p.shortDescription||p.desc||'',badge:p.type||'SOFTWARE TOOL',icon:['⌁','◇','▦','◫'][i%4]}))}}catch(e){products=[...localProducts]}}
function card(p){return `<article class="software-card" data-category="${escapeHtml(p.category)}" data-search="${escapeHtml((p.name+' '+p.desc+' '+p.platform+' '+p.type).toLowerCase())}"><div class="soft-top"><span class="soft-icon">${p.icon||'◇'}</span><span class="soft-badge">${escapeHtml(p.badge||p.type)}</span></div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.desc)}</p><div class="soft-meta"><span>${escapeHtml(p.platform)}</span><span>${escapeHtml(p.type)}</span></div><div class="soft-bottom"><div><small>FROM</small><b>${money(p.price)}</b></div><a href="product.html?slug=${encodeURIComponent(p.slug)}">View Tool <span>→</span></a></div></article>`}
function renderCards(targetId){const el=document.getElementById(targetId);if(!el)return;el.innerHTML=products.map(card).join('')}
function setupCatalogue(){const input=document.getElementById('productSearch');const chips=[...document.querySelectorAll('[data-filter]')];if(!input&&!chips.length)return;let filter='all';function apply(){const q=(input?.value||'').toLowerCase();document.querySelectorAll('.software-card').forEach(c=>{const okFilter=filter==='all'||c.dataset.category.includes(filter);const okSearch=!q||c.dataset.search.includes(q);c.style.display=okFilter&&okSearch?'':'none'})}input?.addEventListener('input',apply);chips.forEach(b=>b.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;apply()}))}
async function submitSellerRegistration(){const payload={sellerName:document.getElementById('sellerName')?.value,email:document.getElementById('sellerEmail')?.value,password:document.getElementById('sellerPassword')?.value,contactName:document.getElementById('contactName')?.value,payoutMethod:document.getElementById('payoutMethod')?.value,bankName:document.getElementById('bankName')?.value,accountHolder:document.getElementById('accountHolder')?.value,accountNumber:document.getElementById('accountNumber')?.value,termsAccepted:document.getElementById('termsAccepted')?.checked};alert(JSON.stringify(await api('/api/seller/register',{method:'POST',body:JSON.stringify(payload)}),null,2))}
async function submitProductListing(){const payload={name:document.getElementById('newProductName')?.value,price:Number(document.getElementById('newProductPrice')?.value||0),platform:document.getElementById('newProductPlatform')?.value,type:document.getElementById('newProductType')?.value,shortDescription:document.getElementById('newProductDesc')?.value};alert(JSON.stringify(await api('/api/seller/products/create',{method:'POST',headers:{'x-demo-user':'u_seller_1'},body:JSON.stringify(payload)}),null,2))}
window.addEventListener('DOMContentLoaded',async()=>{await tryLoadBackendProducts();renderCards('product-grid');renderCards('latest-grid');setupCatalogue()});
