function money(v,type){if(type==='Price on Request')return type;return (type&&type!=='Fixed'?type+' ':'')+'R '+Number(v||0).toLocaleString('en-ZA')}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function json(url,opt){const r=await fetch(url,opt);const x=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw Error(x.error||'Request failed');return x}
function listingCard(x){const img=x.coverImage?`<img class="listing-image" src="${esc(x.coverImage)}" alt="${esc(x.title)}">`:`<div class="mock-img">${esc(x.category)}</div>`;const wa=String(x.whatsapp||'').replace(/\D/g,'');return `<article class="card listing-card">${img}<span class="status approved">${esc(x.listingKind||'listing')}</span><h3>${esc(x.title)}</h3><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description).slice(0,170)}</p><p class="muted">${esc(x.town)}, ${esc(x.province)} · ${esc(x.condition)}</p><div class="listing-actions"><a class="btn secondary" href="listing.html?slug=${encodeURIComponent(x.slug)}">View Details</a>${wa?`<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp</a>`:''}</div></article>`}
async function loadListings(){const el=document.getElementById('listingGrid');if(!el)return;const q=document.getElementById('mq')?.value||'',category=document.getElementById('mcat')?.value||'',province=document.getElementById('mprovince')?.value||'';try{const rows=await json(`/api/listings/public?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&province=${encodeURIComponent(province)}`);el.innerHTML=rows.length?rows.map(listingCard).join(''):'<div class="box">No approved listings found.</div>'}catch(e){el.innerHTML='<div class="notice">Start the Node backend to load marketplace listings.</div>'}}
async function loadDetail(){const el=document.getElementById('listingDetail');if(!el)return;const slug=new URLSearchParams(location.search).get('slug');try{const x=await json('/api/listings/public/'+encodeURIComponent(slug));const photos=(x.images||[]).map((i,n)=>`<img src="${esc(i)}" alt="Listing photo ${n+1}">`).join('');const wa=String(x.whatsapp||'').replace(/\D/g,'');el.innerHTML=`<div class="listing-gallery">${photos||'<div class="mock-img">No photos uploaded</div>'}</div><div class="box"><span class="status approved">Approved listing</span><h1>${esc(x.title)}</h1><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description)}</p><p><b>Category:</b> ${esc(x.category)}</p><p><b>Location:</b> ${esc(x.town)}, ${esc(x.province)}</p><p><b>Condition:</b> ${esc(x.condition)}</p>${x.year?`<p><b>Year:</b> ${esc(x.year)}</p>`:''}${x.usage?`<p><b>Usage:</b> ${esc(x.usage)}</p>`:''}<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp Seller</a><a class="btn secondary" href="tel:${esc(x.phone)}">Call Seller</a></div>`}catch(e){el.innerHTML='<div class="notice">Listing not found.</div>'}}
function preview(){const el=document.getElementById('imagePreview'),inp=document.getElementById('images');if(!el||!inp)return;el.innerHTML='';[...inp.files].slice(0,12).forEach(f=>{const i=document.createElement('img');i.src=URL.createObjectURL(f);el.appendChild(i)})}
async function submitListing(e){e.preventDefault();const out=document.getElementById('result');out.textContent='Uploading...';try{const r=await fetch('/api/listings/create',{method:'POST',headers:{'x-demo-user':'u_seller_1'},body:new FormData(e.target)});const x=await r.json();if(!r.ok)throw Error(x.error||'Upload failed');out.innerHTML='<span class="status pending">Submitted. Waiting for admin approval.</span>';e.target.reset();preview()}catch(err){out.textContent=err.message}}
async function loadAdmin(){const el=document.getElementById('adminListings');if(!el)return;try{const rows=await json('/api/listings/admin/pending',{headers:{'x-demo-user':'u_admin_1'}});el.innerHTML=rows.length?rows.map(x=>`<div class="card">${x.coverImage?`<img class="listing-image" src="${esc(x.coverImage)}">`:''}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="price">${money(x.price,x.priceType)}</div><button onclick="review('${x.id}','approve')">Approve</button><button class="btn danger" onclick="review('${x.id}','reject')">Reject</button></div>`).join(''):'<div class="box">No pending listings.</div>'}catch(e){el.innerHTML='<div class="notice">Could not load listing review.</div>'}}
async function review(id,action){let body='{}';if(action==='reject')body=JSON.stringify({reason:prompt('Reject reason:')||'Rejected by admin'});await json('/api/listings/admin/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body});loadAdmin()}
addEventListener('DOMContentLoaded',()=>{loadListings();loadDetail();loadAdmin();document.getElementById('images')?.addEventListener('change',preview);document.getElementById('listingForm')?.addEventListener('submit',submitListing)});