const MARKETPLACE_API_BASE='https://marketplace-api-o19b.onrender.com';
const marketplaceNativeFetch=window.fetch.bind(window);
function marketplaceApiUrl(input){
  if(typeof input!=='string') return input;
  if(input.startsWith('/api/')||input==='/api') return MARKETPLACE_API_BASE+input;
  if(input.startsWith('/listing-images/')) return MARKETPLACE_API_BASE+input;
  return input;
}
window.fetch=(input,options)=>marketplaceNativeFetch(marketplaceApiUrl(input),options);
async function marketplaceReadJson(response){
  const text=await response.text();
  let data;
  try{data=text?JSON.parse(text):{}}
  catch{throw new Error('Marketplace service returned an invalid response. Please wait a moment and try again.')}
  if(!response.ok)throw new Error(data.error||'Marketplace request failed.');
  return data;
}
const demoListings = [
  {id:'demo-tsc',listingKind:'service',category:'Towing Services',title:'TSC Towing & Roadside Assistance',slug:'demo-tsc-towing',price:850,priceType:'From',condition:'Service',province:'Gauteng',town:'Vanderbijlpark',description:'Demo listing for towing, breakdown recovery and roadside assistance. Replace this preview with the seller’s approved advert and real contact details.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true},
  {id:'demo-tlb',listingKind:'item',category:'TLBs & Earthmoving',title:'2018 CAT 428F2 TLB',slug:'demo-cat-428f2',price:695000,priceType:'Negotiable',condition:'Used',province:'Gauteng',town:'Vereeniging',description:'Demo listing with 5 420 operating hours, general-purpose bucket, rear digging attachment and service history.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true},
  {id:'demo-tractor',listingKind:'item',category:'Tractors',title:'2020 John Deere 6130B Tractor',slug:'demo-john-deere-6130b',price:845000,priceType:'Fixed',condition:'Used',province:'Free State',town:'Bethlehem',description:'Demo listing with 3 160 hours, cab, air conditioning, hydraulic remotes and agricultural tyres.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true},
  {id:'demo-truck',listingKind:'item',category:'Trucks & Bakkies',title:'2019 Isuzu FTR 850 Dropside',slug:'demo-isuzu-ftr-850',price:625000,priceType:'Negotiable',condition:'Used',province:'Gauteng',town:'Boksburg',description:'Demo listing with dropside body and 186 000 km, suitable for equipment and general cargo transport.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true},
  {id:'demo-compressor',listingKind:'item',category:'Industrial Equipment',title:'Atlas Copco 7 Bar Compressor',slug:'demo-atlas-copco-compressor',price:129500,priceType:'Fixed',condition:'Refurbished',province:'Mpumalanga',town:'Secunda',description:'Demo listing for a refurbished portable compressor with 2 880 hours and an inspection record.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true},
  {id:'demo-winch',listingKind:'item',category:'Parts & Accessories',title:'Heavy-Duty Recovery Winch',slug:'demo-recovery-winch',price:18500,priceType:'Fixed',condition:'New',province:'Gauteng',town:'Johannesburg',description:'Demo listing for a recovery winch supplied with controller and mounting hardware.',phone:'',whatsapp:'',images:[],coverImage:'',isDemo:true}
];
function money(v,type){if(type==='Price on Request')return type;return (type&&type!=='Fixed'?type+' ':'')+'R '+Number(v||0).toLocaleString('en-ZA')}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function json(url,opt){const r=await fetch(url,opt);const x=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw Error(x.error||'Request failed');return x}
function waNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0')&&n.length===10)n='27'+n.slice(1);return n.startsWith('27')&&n.length===11?n:''}
function iconFor(c){return ({'Towing Services':'🚚','TLBs & Earthmoving':'🚜','Tractors':'🌾','Trucks & Bakkies':'🚛','Industrial Equipment':'⚙️','Parts & Accessories':'🔩'})[c]||'📦'}
function listingCard(x){
 const img=x.coverImage?`<img class="listing-image" src="${esc(marketplaceApiUrl(x.coverImage))}" alt="${esc(x.title)}">`:`<div class="mock-img demo-visual"><span>${iconFor(x.category)}</span><b>${esc(x.category)}</b></div>`;
 const wa=waNumber(x.whatsapp);
 const details=x.isDemo?'':`<a class="btn secondary" href="listing.html?slug=${encodeURIComponent(x.slug)}">View Details</a>`;
 return `<article class="card listing-card">${img}${x.isDemo?'<span class="demo-ribbon">DEMO LISTING</span>':''}<span class="status approved">${esc(x.listingKind||'listing')}</span><h3>${esc(x.title)}</h3><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description).slice(0,190)}</p><p class="muted">${esc(x.town)}, ${esc(x.province)} · ${esc(x.condition)}</p><div class="listing-actions">${details}${!x.isDemo?`<a class="btn secondary" href="contact-seller.html?listing=${encodeURIComponent(x.slug||x.id)}">Email Seller</a>`:''}${wa?`<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp</a>`:''}${x.isDemo?'<a class="btn secondary" href="seller-listing-create.html">Replace with Real Advert</a>':`<button class="btn warn" onclick="reportListing('${esc(x.id)}')">Report Advert</button>`}</div></article>`
}
function filteredDemo(q,category,province){q=String(q||'').toLowerCase();return demoListings.filter(x=>(!q||(x.title+' '+x.category+' '+x.description).toLowerCase().includes(q))&&(!category||x.category===category)&&(!province||x.province===province))}
async function loadListings(){const el=document.getElementById('listingGrid');if(!el)return;const q=document.getElementById('mq')?.value||'',category=document.getElementById('mcat')?.value||'',province=document.getElementById('mprovince')?.value||'';try{let rows=await json(`/api/listings/public?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&province=${encodeURIComponent(province)}`);if(!rows.length&&(await demoVisibilityEnabled()))rows=filteredDemo(q,category,province);el.innerHTML=rows.length?rows.map(listingCard).join(''):'<div class="box"><b>No approved listings yet.</b><p>Place the first real advert.</p></div>'}catch(e){const rows=(await demoVisibilityEnabled())?filteredDemo(q,category,province):[];el.innerHTML=rows.length?rows.map(listingCard).join(''):'<div class="box"><b>No approved listings yet.</b><p>Demo listings are disabled by Admin.</p></div>'}}
async function loadDetail(){const el=document.getElementById('listingDetail');if(!el)return;const slug=new URLSearchParams(location.search).get('slug');try{const x=await json('/api/listings/public/'+encodeURIComponent(slug));const photos=(x.images||[]).map((i,n)=>`<img src="${esc(marketplaceApiUrl(i))}" alt="Listing photo ${n+1}">`).join('');const wa=waNumber(x.whatsapp);el.innerHTML=`<div class="listing-gallery">${photos||'<div class="mock-img">No photos uploaded</div>'}</div><div class="box"><span class="status approved">Approved listing</span><h1>${esc(x.title)}</h1><div class="price">${money(x.price,x.priceType)}</div><p>${esc(x.description)}</p><p><b>Category:</b> ${esc(x.category)}</p><p><b>Location:</b> ${esc(x.town)}, ${esc(x.province)}</p><p><b>Condition:</b> ${esc(x.condition)}</p>${x.year?`<p><b>Year:</b> ${esc(x.year)}</p>`:''}${x.usage?`<p><b>Usage:</b> ${esc(x.usage)}</p>`:''}${wa?`<a class="btn whatsapp" target="_blank" href="https://wa.me/${wa}?text=${encodeURIComponent('Hi, I am interested in '+x.title)}">WhatsApp Seller</a>`:''}${x.phone?`<a class="btn secondary" href="tel:${esc(x.phone)}">Call Seller</a>`:''}</div>`}catch(e){el.innerHTML='<div class="notice">Listing not found.</div>'}}
function preview(){const el=document.getElementById('imagePreview'),inp=document.getElementById('images');if(!el||!inp)return;el.innerHTML='';[...inp.files].slice(0,12).forEach(f=>{const i=document.createElement('img');i.src=URL.createObjectURL(f);el.appendChild(i)})}
async function submitListing(e){e.preventDefault();const out=document.getElementById('result');out.textContent='Uploading...';try{const r=await fetch('/api/listings/create',{method:'POST',headers:{'x-demo-user':'u_seller_1'},body:new FormData(e.target)});const x=await marketplaceReadJson(r);out.innerHTML='<span class="status pending">Submitted. Waiting for admin approval.</span>';e.target.reset();preview()}catch(err){out.textContent=err.message}}
async function loadAdmin(){const el=document.getElementById('adminListings');if(!el)return;try{const rows=await json('/api/listings/admin/pending',{headers:{'x-demo-user':'u_admin_1'}});el.innerHTML=rows.length?rows.map(x=>`<div class="card">${x.coverImage?`<img class="listing-image" src="${esc(marketplaceApiUrl(x.coverImage))}">`:''}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="price">${money(x.price,x.priceType)}</div><button onclick="review('${x.id}','approve')">Approve</button><button class="btn danger" onclick="review('${x.id}','reject')">Reject</button></div>`).join(''):'<div class="box">No pending listings.</div>'}catch(e){el.innerHTML='<div class="notice">Could not load listing review.</div>'}}
async function review(id,action){let body='{}';if(action==='reject')body=JSON.stringify({reason:prompt('Reject reason:')||'Rejected by admin'});await json('/api/listings/admin/'+id+'/'+action,{method:'POST',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body});loadAdmin()}
addEventListener('DOMContentLoaded',()=>{loadListings();loadDetail();loadAdmin();document.getElementById('images')?.addEventListener('change',preview);document.getElementById('listingForm')?.addEventListener('submit',submitListing)});

const DEMO_VISIBILITY_KEY='stm_demo_listings_enabled';
async function demoVisibilityEnabled(){let enabled=localStorage.getItem(DEMO_VISIBILITY_KEY)!=='false';try{const r=await fetch('/api/marketplace-settings/public/demo-listings',{cache:'no-store'});if(r.ok){const x=await r.json();enabled=x.enabled!==false;localStorage.setItem(DEMO_VISIBILITY_KEY,String(enabled))}}catch(e){}return enabled}
async function enforceDemoVisibility(){const enabled=await demoVisibilityEnabled();document.querySelectorAll('.static-demo').forEach(el=>el.style.display=enabled?'':'none');document.querySelectorAll('.demo-note').forEach(el=>el.style.display=enabled?'':'none');if(!enabled){const grid=document.getElementById('listingGrid');if(grid&&![...grid.children].some(el=>!el.classList.contains('static-demo')))grid.innerHTML='<div class="box no-demo-empty"><b>No approved machinery or service adverts yet.</b><p>Demo listings are disabled by Admin.</p><a class="btn" href="seller-listing-create.html">Place the First Advert</a></div>'}}
addEventListener('DOMContentLoaded',enforceDemoVisibility);

async function reportListing(id){const reason=prompt('Why are you reporting this advert?');if(!reason)return;try{const r=await fetch('/api/marketplace-live/public/report/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const x=await r.json();if(!r.ok)throw Error(x.error||'Report failed');alert('Report received. Reference: '+x.reference)}catch(e){alert(e.message)}}
