const r=require('express').Router();
const{requireRole}=require('../auth');
const{readDb,writeDb,addEvent}=require('../db');
const n=v=>Number(v||0);
const iso=v=>{const d=new Date(v||0);return isNaN(d)?null:d};
function inRange(x,from,to){const d=iso(x);if(!d)return false;return(!from||d>=new Date(from))&&(!to||d<=new Date(to+'T23:59:59.999Z'))}
function lines(db,from,to){
 const orders=(db.orders||[]).filter(o=>inRange(o.createdAt,from,to));
 const ledger=(db.payoutLedger||[]).filter(x=>inRange(x.createdAt,from,to));
 return orders.map(o=>{const l=ledger.find(x=>x.orderId===o.id)||{};return{orderId:o.id,reference:o.ref||'',date:o.createdAt,buyer:o.buyerEmail||'',sellerId:l.sellerId||'',gross:n(o.total),commission:n(l.platformFee),gatewayFee:n(o.gatewayFee),sellerPayable:n(l.sellerAmount),paymentStatus:o.status||'unknown',payoutStatus:l.status||'not_ready',payfastPaymentId:o.payfastPaymentId||'',refundAmount:n(o.refundAmount),invoiceNumber:o.invoiceNumber||''}})
}
r.get('/summary',requireRole('admin'),(req,res)=>{const db=readDb(),rows=lines(db,req.query.from,req.query.to);const sum=k=>rows.reduce((a,x)=>a+n(x[k]),0);const pending=(db.checkoutIntents||[]).filter(x=>x.status==='created').length;res.json({period:{from:req.query.from||'',to:req.query.to||''},totals:{grossSales:sum('gross'),commission:sum('commission'),gatewayFees:sum('gatewayFee'),sellerPayable:sum('sellerPayable'),refunds:sum('refundAmount'),netPlatformRevenue:sum('commission')-sum('gatewayFee'),paidOrders:rows.filter(x=>x.paymentStatus==='paid').length,pendingPayments:pending,pendingPayouts:rows.filter(x=>['pending','ready','not_ready'].includes(x.payoutStatus)).length,paidPayouts:rows.filter(x=>x.payoutStatus==='paid_out').length},operations:{activeListings:(db.physicalListings||[]).filter(x=>x.status==='active'&&x.approvalStatus==='approved').length,pendingListings:(db.physicalListings||[]).filter(x=>x.approvalStatus==='pending').length,pendingSellers:(db.sellerApplications||[]).filter(x=>x.status==='pending').length,openReports:(db.listingReports||[]).filter(x=>x.status==='open').length},transactions:rows})});
r.get('/export.csv',requireRole('admin'),(req,res)=>{const rows=lines(readDb(),req.query.from,req.query.to),h=['Order ID','Reference','Date','Buyer','Seller ID','Gross','Commission','Gateway Fee','Seller Payable','Payment Status','Payout Status','PayFast ID','Refund','Invoice'];const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[h,...rows.map(x=>[x.orderId,x.reference,x.date,x.buyer,x.sellerId,x.gross,x.commission,x.gatewayFee,x.sellerPayable,x.paymentStatus,x.payoutStatus,x.payfastPaymentId,x.refundAmount,x.invoiceNumber])].map(a=>a.map(esc).join(',')).join('\n');res.type('text/csv').set('Content-Disposition','attachment; filename="Marketplace_Finance_Export.csv"').send(csv)});
r.post('/refund/:orderId',requireRole('admin'),(req,res)=>{const db=readDb(),o=(db.orders||[]).find(x=>x.id===req.params.orderId);if(!o)return res.status(404).json({error:'Order not found'});const amount=n(req.body.amount);if(amount<=0||amount>n(o.total))return res.status(400).json({error:'Invalid refund amount'});o.refundAmount=amount;o.status=amount===n(o.total)?'refunded':'partially_refunded';o.refundReason=String(req.body.reason||'Admin refund').slice(0,300);o.refundedAt=new Date().toISOString();(db.payoutLedger||[]).filter(x=>x.orderId===o.id).forEach(x=>{x.status='reversed';x.reversalAmount=amount});writeDb(db);addEvent('admin.refund_recorded','Refund recorded',{orderId:o.id,amount,by:req.currentUser.id});res.json({ok:true,order:o})});
module.exports=r;
