const express=require('express'),multer=require('multer'),path=require('path'),fs=require('fs');
const config=require('../config');const{requireRole}=require('../auth');const{readDb,writeDb,addEvent}=require('../db');
const r=express.Router();fs.mkdirSync(config.listingImageDir,{recursive:true});
const allowed=new Set(['.jpg','.jpeg','.png','.webp']);
const upload=multer({dest:config.uploadDir,limits:{fileSize:10*1024*1024,files:12},fileFilter:(req,file,cb)=>cb(null,allowed.has(path.extname(file.originalname).toLowerCase()))});
function clean(v,n=500){return String(v||'').trim().slice(0,n)}
function slugify(v){return clean(v,100).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now()}
function publicListing(x){return {...x,phone:x.phone||'',whatsapp:x.whatsapp||''}}
r.get('/public',(req,res)=>{let rows=(readDb().physicalListings||[]).filter(x=>x.status==='active'&&x.approvalStatus==='approved');const q=clean(req.query.q,100).toLowerCase(),cat=clean(req.query.category,80),province=clean(req.query.province,80);if(q)rows=rows.filter(x=>(x.title+' '+x.description+' '+x.category+' '+x.town).toLowerCase().includes(q));if(cat)rows=rows.filter(x=>x.category===cat);if(province)rows=rows.filter(x=>x.province===province);res.json(rows.map(publicListing))});
r.get('/public/:slug',(req,res)=>{const x=(readDb().physicalListings||[]).find(x=>x.slug===req.params.slug&&x.status==='active'&&x.approvalStatus==='approved');if(!x)return res.status(404).json({error:'Listing not found'});res.json(publicListing(x))});
r.post('/create',requireRole('seller'),upload.array('images',12),(req,res)=>{const db=readDb();if(!clean(req.body.title)||!clean(req.body.category)||!clean(req.body.description))return res.status(400).json({error:'Title, category and description are required'});const id='listing_'+Date.now();const imgs=(req.files||[]).map((file,i)=>{const ext=path.extname(file.originalname).toLowerCase();const name=id+'_'+(i+1)+ext;fs.renameSync(file.path,path.join(config.listingImageDir,name));return '/listing-images/'+name});const x={id,sellerId:req.currentUser.id,listingKind:clean(req.body.listingKind||'item',30),category:clean(req.body.category,80),title:clean(req.body.title,120),slug:slugify(req.body.title),price:Number(req.body.price||0),priceType:clean(req.body.priceType||'Fixed',30),make:clean(req.body.make,60),model:clean(req.body.model,60),year:clean(req.body.year,10),usage:clean(req.body.usage,40),condition:clean(req.body.condition,40),province:clean(req.body.province,60),town:clean(req.body.town,80),description:clean(req.body.description,3000),phone:clean(req.body.phone,30),whatsapp:clean(req.body.whatsapp,30).replace(/\D/g,''),images:imgs,coverImage:imgs[0]||'',status:'draft',approvalStatus:'pending',createdAt:new Date().toISOString(),approvedAt:'',approvedBy:'',rejectReason:''};db.physicalListings=db.physicalListings||[];db.physicalListings.unshift(x);writeDb(db);addEvent('seller.listing_submitted','Physical listing submitted',{listingId:id});res.json({ok:true,listing:x})});
r.get('/mine',requireRole('seller'),(req,res)=>res.json((readDb().physicalListings||[]).filter(x=>x.sellerId===req.currentUser.id)));
r.post('/:id/status',requireRole('seller'),(req,res)=>{const db=readDb(),x=(db.physicalListings||[]).find(x=>x.id===req.params.id&&x.sellerId===req.currentUser.id);if(!x)return res.status(404).json({error:'Listing not found'});const status=clean(req.body.status,20);if(!['active','paused','sold','draft'].includes(status))return res.status(400).json({error:'Invalid status'});x.status=status;writeDb(db);res.json({ok:true,listing:x})});
r.get('/admin/pending',requireRole('admin'),(req,res)=>res.json((readDb().physicalListings||[]).filter(x=>x.approvalStatus==='pending')));
r.post('/admin/:id/approve',requireRole('admin'),(req,res)=>{const db=readDb(),x=(db.physicalListings||[]).find(x=>x.id===req.params.id);if(!x)return res.status(404).json({error:'Listing not found'});x.status='active';x.approvalStatus='approved';x.approvedAt=new Date().toISOString();x.approvedBy=req.currentUser.id;writeDb(db);res.json({ok:true,listing:x})});
r.post('/admin/:id/reject',requireRole('admin'),(req,res)=>{const db=readDb(),x=(db.physicalListings||[]).find(x=>x.id===req.params.id);if(!x)return res.status(404).json({error:'Listing not found'});x.status='rejected';x.approvalStatus='rejected';x.rejectReason=clean(req.body.reason||'Rejected',300);writeDb(db);res.json({ok:true,listing:x})});
r.post('/public/:id/report',(req,res)=>{const db=readDb();db.listingReports=db.listingReports||[];db.listingReports.unshift({id:'report_'+Date.now(),listingId:req.params.id,reason:clean(req.body.reason,500),createdAt:new Date().toISOString(),status:'open'});writeDb(db);res.json({ok:true})});
module.exports=r;