const r=require('express').Router();const nodemailer=require('nodemailer');
const{requireRole}=require('../auth');const{readDb,writeDb,addEvent}=require('../db');
function clean(v,n=1000){return String(v||'').trim().slice(0,n)}
function emailOk(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||''))}
function normalizeWhatsApp(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0')&&n.length===10)n='27'+n.slice(1);if(n.startsWith('27')&&n.length===11)return n;return ''}
function listing(db,id){return(db.physicalListings||[]).find(x=>x.id===id||x.slug===id)}
r.get('/public/contact/:id',(req,res)=>{const db=readDb(),x=listing(db,req.params.id);if(!x||x.status!=='active'||x.approvalStatus!=='approved')return res.status(404).json({error:'Advert not found'});res.json({listingId:x.id,title:x.title,phone:x.phone||'',whatsapp:normalizeWhatsApp(x.whatsapp),emailAvailable:true})});
r.post('/public/contact/:id/email',(req,res)=>{const db=readDb(),x=listing(db,req.params.id);if(!x||x.status!=='active'||x.approvalStatus!=='approved')return res.status(404).json({error:'Advert not found'});const name=clean(req.body.name,80),email=clean(req.body.email,160),message=clean(req.body.message,2000),hp=clean(req.body.website,100);if(hp)return res.status(400).json({error:'Message blocked'});if(!name||!emailOk(email)||message.length<10)return res.status(400).json({error:'Enter your name, valid email and a proper message'});db.listingMessages=db.listingMessages||[];const m={id:'msg_'+Date.now(),listingId:x.id,sellerId:x.sellerId,buyerName:name,buyerEmail:email,message,status:'new',createdAt:new Date().toISOString()};db.listingMessages.unshift(m);writeDb(db);addEvent('buyer.listing_message','Buyer sent seller enquiry',{messageId:m.id,listingId:x.id});res.json({ok:true,reference:m.id,message:'Your message was sent to the seller queue.'})});
r.post('/public/report/:id',(req,res)=>{const db=readDb(),x=listing(db,req.params.id);if(!x)return res.status(404).json({error:'Advert not found'});const reason=clean(req.body.reason,500);if(reason.length<5)return res.status(400).json({error:'Please provide a report reason'});db.listingReports=db.listingReports||[];const item={id:'report_'+Date.now(),listingId:x.id,reason,email:clean(req.body.email,160),status:'open',createdAt:new Date().toISOString()};db.listingReports.unshift(item);writeDb(db);addEvent('buyer.listing_reported','Listing reported',{reportId:item.id,listingId:x.id});res.json({ok:true,reference:item.id})});
r.get('/seller/mine',requireRole('seller'),(req,res)=>res.json((readDb().physicalListings||[]).filter(x=>x.sellerId===req.currentUser.id)));
r.patch('/seller/:id',requireRole('seller'),(req,res)=>{const db=readDb(),x=(db.physicalListings||[]).find(x=>x.id===req.params.id&&x.sellerId===req.currentUser.id);if(!x)return res.status(404).json({error:'Advert not found'});for(const k of ['title','description','town','province','condition','priceType','phone','whatsapp'])if(req.body[k]!==undefined)x[k]=clean(req.body[k],k==='description'?3000:160);if(req.body.price!==undefined)x.price=Number(req.body.price||0);x.approvalStatus='pending';x.status='draft';x.updatedAt=new Date().toISOString();writeDb(db);res.json({ok:true,listing:x,message:'Changes saved and sent for approval.'})});
r.post('/seller/:id/status',requireRole('seller'),(req,res)=>{const db=readDb(),x=(db.physicalListings||[]).find(x=>x.id===req.params.id&&x.sellerId===req.currentUser.id);if(!x)return res.status(404).json({error:'Advert not found'});const status=clean(req.body.status,20);if(!['active','paused','sold','deleted'].includes(status))return res.status(400).json({error:'Invalid advert status'});x.status=status;x.updatedAt=new Date().toISOString();writeDb(db);res.json({ok:true,listing:x})});
r.get('/admin/reports',requireRole('admin'),(req,res)=>res.json(readDb().listingReports||[]));
r.get('/admin/messages',requireRole('admin'),(req,res)=>res.json(readDb().listingMessages||[]));
r.post('/admin/listing/:id/action',requireRole('admin'),(req,res)=>{const db=readDb(),x=listing(db,req.params.id);if(!x)return res.status(404).json({error:'Advert not found'});const action=clean(req.body.action,30);if(action==='suspend')x.status='suspended';else if(action==='activate'){x.status='active';x.approvalStatus='approved'}else if(action==='feature')x.featured=true;else if(action==='unfeature')x.featured=false;else return res.status(400).json({error:'Invalid action'});x.adminNote=clean(req.body.note,500);writeDb(db);addEvent('admin.listing_action','Admin changed an advert',{listingId:x.id,action});res.json({ok:true,listing:x})});
r.get('/public/seo/listings',(req,res)=>{const db=readDb();res.json((db.physicalListings||[]).filter(x=>x.status==='active'&&x.approvalStatus==='approved').map(x=>({slug:x.slug,updated:x.updatedAt||x.approvedAt||x.createdAt}))) });
module.exports=r;