const express=require('express'),multer=require('multer'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const config=require('../config'),{requireRole}=require('../auth'),{readDb,writeDb,addEvent}=require('../db');
const r=express.Router(),tmp=path.join(config.uploadDir,'admin-cockpit');
[tmp,config.productImageDir,config.productPackageDir,config.productDocumentDir].forEach(d=>fs.mkdirSync(d,{recursive:true}));
const upload=multer({dest:tmp,limits:{fileSize:config.uploadMaxMb*1024*1024,files:22}});
const safe=s=>String(s||'file').trim().replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^_+|_+$/g,'')||'file';
const slug=s=>String(s||'product').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const move=(src,dst)=>{fs.mkdirSync(path.dirname(dst),{recursive:true});if(fs.existsSync(dst))fs.unlinkSync(dst);fs.renameSync(src,dst)};
const cleanup=files=>Object.values(files||{}).flat().forEach(f=>{if(fs.existsSync(f.path))fs.unlinkSync(f.path)});
const product=(db,id)=>db.products.find(x=>x.id===id);
const snapshot=p=>({at:new Date().toISOString(),name:p.name,price:p.price,status:p.status,approvalStatus:p.approvalStatus,image:p.image||'',packageName:p.packageName||'',packageVersion:p.packageVersion||''});

r.get('/products',requireRole('admin'),(req,res)=>res.json((readDb().products||[]).map(p=>({...p,packagePath:undefined})).sort((a,b)=>a.name.localeCompare(b.name))));
r.post('/save',requireRole('admin'),upload.fields([{name:'image',maxCount:1},{name:'package',maxCount:1},{name:'documents',maxCount:20}]),(req,res)=>{
 try{const db=readDb();let p=req.body.productId?product(db,req.body.productId):null;const name=String(req.body.name||'').trim();if(!p&&!name)throw Error('Product name is required.');
  if(!p){const now=Date.now();p={id:'p_admin_'+now,sellerId:req.currentUser.id,name,slug:slug(name)+'-'+now,createdAt:new Date().toISOString(),status:'draft',approvalStatus:'pending',documentFiles:[],releaseHistory:[]};db.products.unshift(p)}
  p.releaseHistory=p.releaseHistory||[];p.releaseHistory.unshift(snapshot(p));p.releaseHistory=p.releaseHistory.slice(0,20);
  ['name','category','platform','type','salesMode','shortDescription','desc','releaseNotes'].forEach(k=>{if(req.body[k]!==undefined)p[k]=String(req.body[k]).trim()});
  if(req.body.price!=='')p.price=Math.max(0,Number(req.body.price)||0);
  const im=req.files?.image?.[0];if(im){const ext=path.extname(im.originalname).toLowerCase();if(!['.jpg','.jpeg','.png','.webp'].includes(ext))throw Error('Photo must be JPG, PNG or WebP.');const fn=safe(p.slug)+ext;move(im.path,path.join(config.productImageDir,fn));p.image='/product-images/'+fn;p.imageUploadedAt=new Date().toISOString()}
  const pack=req.files?.package?.[0];if(pack){if(path.extname(pack.originalname).toLowerCase()!=='.zip')throw Error('Production package must be one ZIP file.');const dst=path.join(config.productPackageDir,safe(p.slug),safe(pack.originalname));move(pack.path,dst);p.packagePath=dst;p.packageName=pack.originalname;p.packageSize=pack.size;p.packageSha256=sha(dst);p.packageVersion=String(req.body.packageVersion||'1.0').trim();p.packageUploadedAt=new Date().toISOString();p.packageActive=true}
  const docs=req.files?.documents||[];p.documentFiles=p.documentFiles||[];for(const d of docs){const ext=path.extname(d.originalname).toLowerCase();if(!['.pdf','.docx','.txt','.xlsx','.jpg','.jpeg','.png'].includes(ext)){if(fs.existsSync(d.path))fs.unlinkSync(d.path);continue}const fn=Date.now()+'_'+safe(d.originalname),dst=path.join(config.productDocumentDir,safe(p.slug),fn);move(d.path,dst);p.documentFiles.push({id:'doc_'+Date.now()+'_'+Math.random().toString(16).slice(2,6),name:d.originalname,size:d.size,path:dst,sha256:sha(dst),uploadedAt:new Date().toISOString()})}
  if(req.body.workflow==='live'){p.status='active';p.approvalStatus='approved';p.approvedAt=new Date().toISOString();p.approvedBy=req.currentUser.id}else if(req.body.workflow==='offline'){p.status='offline'}else if(req.body.workflow==='draft'){p.status='draft';p.approvalStatus='pending'}
  p.updatedAt=new Date().toISOString();writeDb(db);addEvent('admin.product_cockpit_saved','Product cockpit saved',{productId:p.id});res.json({ok:true,product:{...p,packagePath:undefined}})
 }catch(e){cleanup(req.files);res.status(400).json({error:e.message})}
});
r.post('/:id/action',requireRole('admin'),(req,res)=>{const db=readDb(),p=product(db,req.params.id);if(!p)return res.status(404).json({error:'Product not found'});const a=req.body.action;p.releaseHistory=p.releaseHistory||[];p.releaseHistory.unshift(snapshot(p));if(a==='live'){p.status='active';p.approvalStatus='approved';p.approvedAt=new Date().toISOString();p.approvedBy=req.currentUser.id}else if(a==='offline')p.status='offline';else if(a==='draft'){p.status='draft';p.approvalStatus='pending'}else if(a==='archive')p.status='archived';else if(a==='restore'){p.status='active';p.approvalStatus='approved'}else return res.status(400).json({error:'Invalid action'});p.updatedAt=new Date().toISOString();writeDb(db);addEvent('admin.product_action','Admin product action',{productId:p.id,action:a});res.json({ok:true,product:p})});
r.post('/:id/remove-image',requireRole('admin'),(req,res)=>{const db=readDb(),p=product(db,req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(p.image&&p.image.startsWith('/product-images/')){const f=path.join(config.productImageDir,path.basename(p.image));if(fs.existsSync(f))fs.unlinkSync(f)}p.image='';writeDb(db);res.json({ok:true})});
r.post('/:id/remove-package',requireRole('admin'),(req,res)=>{const db=readDb(),p=product(db,req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(p.packagePath&&fs.existsSync(p.packagePath))fs.unlinkSync(p.packagePath);['packagePath','packageName','packageSize','packageSha256','packageVersion','packageUploadedAt'].forEach(k=>delete p[k]);p.packageActive=false;writeDb(db);res.json({ok:true})});
r.delete('/:id/documents/:docId',requireRole('admin'),(req,res)=>{const db=readDb(),p=product(db,req.params.id);if(!p)return res.status(404).json({error:'Not found'});const d=(p.documentFiles||[]).find(x=>x.id===req.params.docId);if(d?.path&&fs.existsSync(d.path))fs.unlinkSync(d.path);p.documentFiles=(p.documentFiles||[]).filter(x=>x.id!==req.params.docId);writeDb(db);res.json({ok:true})});
r.get('/:id/package',requireRole('admin'),(req,res)=>{const p=product(readDb(),req.params.id);if(!p?.packagePath||!fs.existsSync(p.packagePath))return res.status(404).send('Package not found');res.download(p.packagePath,p.packageName)});
r.get('/:id/documents/:docId',requireRole('admin'),(req,res)=>{const p=product(readDb(),req.params.id),d=(p?.documentFiles||[]).find(x=>x.id===req.params.docId);if(!d?.path||!fs.existsSync(d.path))return res.status(404).send('Document not found');res.download(d.path,d.name)});
r.delete('/:id',requireRole('admin'),(req,res)=>{const db=readDb(),p=product(db,req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(String(req.body.confirmName||'')!==p.name)return res.status(400).json({error:'Product name confirmation does not match'});p.status='removed';p.approvalStatus='removed';p.removedAt=new Date().toISOString();writeDb(db);res.json({ok:true})});
module.exports=r;
